name: guardian_pet_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  rxdart: ^0.27.7
  dio: ^5.1.2
  equatable: ^2.0.5
  modular_bloc_bind: ^1.0.1
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_bloc: ^8.1.3
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_crashlytics: ^3.0.15
  shared_preferences: ^2.0.8
  google_fonts: ^4.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4
  mocktail: ^0.3.0
  bloc_test: ^9.1.2


  flutter_lints: ^2.0.0


flutter:

  generate: true
  uses-material-design: true


  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
