// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8kdcXKfDCFYo4RoowpZZnaLb_ECKuFRU',
    appId: '1:968781617160:web:fc935f6ba77176cf4fd9bd',
    messagingSenderId: '968781617160',
    projectId: 'pet-guardian-80461',
    authDomain: 'pet-guardian-80461.firebaseapp.com',
    storageBucket: 'pet-guardian-80461.appspot.com',
    measurementId: 'G-4D00FBY3C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn2D9qroamshzm8HYFUVwAzlZPNNl-c4w',
    appId: '1:968781617160:android:4c94ef2d65ddc1e94fd9bd',
    messagingSenderId: '968781617160',
    projectId: 'pet-guardian-80461',
    storageBucket: 'pet-guardian-80461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlm25oGlc8YuNsb-QzHtPI4jlYoaDpwY',
    appId: '1:968781617160:ios:41b501e9eedc876e4fd9bd',
    messagingSenderId: '968781617160',
    projectId: 'pet-guardian-80461',
    storageBucket: 'pet-guardian-80461.appspot.com',
    iosClientId: '968781617160-8p848dkra8bhjpaf5v1u4tsnkh78uvlr.apps.googleusercontent.com',
    iosBundleId: 'com.aspc.guardianPetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTlm25oGlc8YuNsb-QzHtPI4jlYoaDpwY',
    appId: '1:968781617160:ios:e72fd97573c7a50b4fd9bd',
    messagingSenderId: '968781617160',
    projectId: 'pet-guardian-80461',
    storageBucket: 'pet-guardian-80461.appspot.com',
    iosClientId: '968781617160-v84ust8abn5j90vhptqo5fel0msnsbuu.apps.googleusercontent.com',
    iosBundleId: 'com.aspc.guardianPetApp.RunnerTests',
  );
}
